In [2]:
println("Hello")

Hello


In [6]:
ans1 = 42
typeof(ans1)

Int64

In [5]:
ans2 = 42.0
typeof(ans2)

Float64

In [ ]:
# Commenting in Julia

In [ ]:
#=

Multiline commenting

=#

In [8]:
power = 10^2

100

In [9]:
# '' defines a char, "" defines a string.
typeof('a')

Char

In [10]:
typeof("a")

String

In [11]:
# $ used to enter variables into string.
age = 15
println("John is $age years old")

John is 15 years old


In [ ]:
# Tuples, arrays ordered. Tuples cant change contents. Dictionaries not ordered.
# Cant index in dictionary.

In [13]:
dictionary = Dict("Name" => "John", "Age" => 15)

Dict{String, Any} with 2 entries:
  "Age"  => 15
  "Name" => "John"

In [15]:
dictionary["Age"]

15

In [ ]:
# pop!(dictionary, "Age") will delete the age key.

In [16]:
tuple = ("cats", "dogs", "birds")

("cats", "dogs", "birds")

In [17]:
# Indexing starts with 1 not 0.
tuple[1]

"cats"

In [19]:
array = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [20]:
array[1]

1

In [22]:
array[2] = 4

4

In [23]:
array

3-element Vector{Int64}:
 1
 4
 3

In [25]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5


In [26]:
for n in 1:5
    println(n)
end

1
2
3
4
5


In [27]:
A = zeros(3, 4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [31]:
for i in 1:3, j in 1:4
    A[i, j] = i + j
end
A

3×4 Matrix{Float64}:
 2.0  3.0  4.0  5.0
 3.0  4.0  5.0  6.0
 4.0  5.0  6.0  7.0

In [32]:
C = [i + j for i in 1:3, j in 1:4]
C

3×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7

In [33]:
x = 5
y = 7
if x > y
    println("$x is larger than $y")
elseif y > x
    println("$y is larger than $x")
else
    println("equal")
end

7 is larger than 5


In [34]:
# The following conditional statement is equal to the following ternary operator.
#=
if a
    b
else
    c
end
=#
# a ? b : c
(x > y) ? x : y

7

In [35]:
(x > y) && println("$x is larger than $y")

false

In [36]:
(y > x) && println("$y is larger than $x")

7 is larger than 5


In [39]:
function sayhi(name)
    println("hi $name")
end
sayhi("Tim")

hi Tim


In [40]:
function f(x)
    x^2
end
f(5)

25

In [41]:
# Can also create funciotn in a single line
sayhi2(name) = println("hi $name")
f2(x) = x^2

f2 (generic function with 1 method)

In [42]:
# Can also define them as maps.
sayhi3 = name -> println("hi $name")
f3 = x -> x^2

#5 (generic function with 1 method)

In [ ]:
# function(v) will output something without changing v.
# function!(v) will change v to the output.
# ! is pronounced bang

In [ ]:
# f(x) will perform f on x.
# f.(x) will perform f on each element of x. This is broadcasting.